//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nMars.IDE.Properties {
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class IDESettings : global::System.Configuration.ApplicationSettingsBase {
    
        private static IDESettings defaultInstance = ((IDESettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IDESettings())));
        
        public static IDESettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public System.Collections.Generic.List<string> RecentProjects {
            get {
                return ((System.Collections.Generic.List<string>)(this["RecentProjects"]));
            }
            set {
                this["RecentProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadRecentProject {
            get {
                return ((bool)(this["LoadRecentProject"]));
            }
            set {
                this["LoadRecentProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nMars.Engine-StepBack")]
        public string DefaultEngine {
            get {
                return ((string)(this["DefaultEngine"]));
            }
            set {
                this["DefaultEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nMars.Parser")]
        public string DefaultParser {
            get {
                return ((string)(this["DefaultParser"]));
            }
            set {
                this["DefaultParser"] = value;
            }
        }
    }
}
